package com.hp.il.maven;

import junit.framework.TestCase;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;

/**
 * Created with IntelliJ IDEA.
 * User: elimeleh
 * Date: 09/12/12
 * Time: 13:16
 * To change this template use File | Settings | File Templates.
 */
public class GenerateSchemaNameMojoTest extends TestCase {

    private GenerateSchemaNameMojo generatedMojo;

    private String LONGER_THAN_20_PREFIX = "prefix_longer_than_20_chars";
    private String SHORTER_THAN_20_PREFIX = "prefix";

    protected void setUp() throws Exception {
        generatedMojo = new GenerateSchemaNameMojo();
    }


    /**
     * @Test
     * set default values to all plugin parameters and runs execute
     */
    public void testDefaultMojoExecute() throws MojoExecutionException, MojoFailureException {

        generatedMojo.setPrefix("");
        generatedMojo.setGeneratedUniqueIdLength(10);
        generatedMojo.setSchemaNameLength(30);

        generatedMojo.execute();

       String schemaName = generatedMojo.getSchemaName();
        assertTrue(schemaName!=null && schemaName.length()==30 && generatedMojo.getGeneratedUniqueIdLength()==30);
    }

    /**
     * @Test
     *  prefix  value longer than 20 characters
     */
    public void testMojoExecuteLongPrefixCase() throws MojoExecutionException, MojoFailureException {

        generatedMojo.setPrefix(LONGER_THAN_20_PREFIX);

        //RandomSequenceLength and SchemaNameLength default values
        generatedMojo.setGeneratedUniqueIdLength(10);
        generatedMojo.setSchemaNameLength(30);

        generatedMojo.execute();

        String schemaName = generatedMojo.getSchemaName();
        assertTrue(schemaName!=null && generatedMojo.getGeneratedUniqueIdLength()==10 && generatedMojo.getPrefix().length()==20);
    }

    /**
     * @Test
     *  prefix  value shorter than 20 characters
     */
    public void testMojoExecuteShortPrefixCase() throws MojoExecutionException, MojoFailureException {

        generatedMojo.setPrefix(SHORTER_THAN_20_PREFIX);

        //RandomSequenceLength and SchemaNameLength default values
        generatedMojo.setGeneratedUniqueIdLength(10);
        generatedMojo.setSchemaNameLength(30);

        generatedMojo.execute();

        String schemaName = generatedMojo.getSchemaName();
        assertTrue(schemaName!=null && schemaName.length()==30 && generatedMojo.getGeneratedUniqueIdLength()==(30-SHORTER_THAN_20_PREFIX.length())-"-".length());
    }

    /**
     * @Test
     *  tests difference between schemaNames generated by two different executions
     */
    public void testMojoExecuteDiff() throws MojoExecutionException, MojoFailureException {

        //RandomSequenceLength and SchemaNameLength default values
        generatedMojo.setGeneratedUniqueIdLength(10);
        generatedMojo.setSchemaNameLength(30);

        //first execution
        generatedMojo.execute();
        String firstSchemaName = generatedMojo.getSchemaName();

        //second execution
        generatedMojo.execute();
        String secondSchemaName = generatedMojo.getSchemaName();

        boolean equals = firstSchemaName.equals(secondSchemaName);

        assertFalse(equals);
    }

}
